src/main/java/com/um5s/labos/DAO/beans/Travail/Equipe.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.um5s.labos.DAO.beans.Travail;

import com.um5s.labos.DAO.beans.Profil.Membre;
import com.um5s.labos.DAO.beans.Profil.ChefEquipe;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 *
 * @author l.IsSaM.l
 */
@Entity
public class Equipe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Equipe_ID")
    private long id;
    private String nom;
    private String Description;
    private Date dateCreation;

    @OneToOne
    @JoinColumn(name = "User_Id")
    private ChefEquipe ChefEquipe;


    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Labo_ID")
    private Laboratoire laboratoire;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Centre_ID")
    private CentreRecherche centreRecherche;

    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name = "Equipe_ID")
    private Set<DomaineRecherche> listDomaines = new HashSet<DomaineRecherche>();



    public Equipe(String nom, String Description) {
        this.nom = nom;
        this.Description = Description;
    }

    public Equipe() {
    }

    public Equipe(String nom, String Description, Date dateCreation, ChefEquipe ChefEquipe, Laboratoire laboratoire, CentreRecherche centreRecherche) {
        this.nom = nom;
        this.Description = Description;
        this.dateCreation = dateCreation;
        this.ChefEquipe = ChefEquipe;
        this.laboratoire = laboratoire;
        this.centreRecherche = centreRecherche;
    }


    public Equipe(String nom, String description, Date dateCreation) {
        this.nom = nom;
        Description = description;
        this.dateCreation = dateCreation;
    }

    public long getId() {
        return id;
    }

    public String getNom() {
        return nom;
    }

    public String getDescription() {
        return Description;
    }

    public Date getDateCreation() {
        return dateCreation;
    }

    public ChefEquipe getChefEquipe() {
        return ChefEquipe;
    }

    public Laboratoire getLaboratoire() {
        return laboratoire;
    }

    public CentreRecherche getCentreRecherche() {
        return centreRecherche;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    public void setChefEquipe(ChefEquipe ChefEquipe) {
        this.ChefEquipe = ChefEquipe;
    }

    public void setLaboratoire(Laboratoire laboratoire) {
        this.laboratoire = laboratoire;
    }

    public void setCentreRecherche(CentreRecherche centreRecherche) {
        this.centreRecherche = centreRecherche;
    }

    public Set<DomaineRecherche> getListDomaines() {
        return listDomaines;
    }

    public void setListDomaines(Set<DomaineRecherche> listDomaines) {
        this.listDomaines = listDomaines;
    }



}

src/main/java/com/um5s/labos/DAO/beans/Travail/Laboratoire.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.um5s.labos.DAO.beans.Travail;


import com.um5s.labos.DAO.beans.Profil.AdministrateurLabo;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

/**
 *
 * @author l.IsSaM.l
 */
@Entity
public class Laboratoire {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "Labo_ID")
    private long id;
    private String nom;
    private String adresse;
    private String Description;


    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Centre_ID")
    private CentreRecherche centreRecherche;

    @OneToOne
    @JoinColumn(name="User_id")
    private AdministrateurLabo administrateurLabo;

    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name = "Labo_ID")
    private Set<Equipe> listEquipes = new HashSet<Equipe>();

    @OneToMany(cascade = CascadeType.ALL)
    @JoinColumn(name = "Labo_ID")
    private Set<DomaineRecherche> listDomaines = new HashSet<DomaineRecherche>();

    public Laboratoire(String nom, String adresse, String Description) {
        this.nom = nom;
        this.adresse = adresse;
        this.Description = Description;
    }

    public Laboratoire() {
    }


    public long getId() {
        return id;
    }

    public String getNom() {
        return nom;
    }

    public String getAdresse() {
        return adresse;
    }

    public String getDescription() {
        return Description;
    }

    public CentreRecherche getCentreRecherche() {
        return centreRecherche;
    }



    public void setId(long id) {
        this.id = id;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public void setCentreRecherche(CentreRecherche centreRecherche) {
        this.centreRecherche = centreRecherche;
    }

    public AdministrateurLabo getAdministrateurLabo() {
        return administrateurLabo;
    }

    public void setAdministrateurLabo(AdministrateurLabo administrateurLabo) {
        this.administrateurLabo = administrateurLabo;
    }



    @Override
    public String toString() {
        return "Laboratoire{" + "id=" + id + ", nom=" + nom + ", adresse=" + adresse + ", Description=" + Description + ", centreRecherche=" + centreRecherche + '}';
    }

    public Set<Equipe> getListEquipes() {
        return listEquipes;
    }

    public void setListEquipes(Set<Equipe> listEquipes) {
        this.listEquipes = listEquipes;
    }

    public Set<DomaineRecherche> getListDomaines() {
        return listDomaines;
    }

    public void setListDomaines(Set<DomaineRecherche> listDomaines) {
        this.listDomaines = listDomaines;
    }


}

src/main/webapp/landing page/about.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>A propos de nous</title>
</h:head>

<ui:include src="head.xhtml"></ui:include>

<h:body>

        <!-- Blog-top start -->
        <section class="blog-post-top">
            <div class="container">
                <div class="row">

                    <div class="col-xs-12">
                        <ul class="blog-post-menu fix">
                            <li class="active"><a href="">Recent</a></li>
                            <li><a href="">Most Popular</a></li>
                            <li><a href="">Most Viwed</a></li>
                        </ul>
                    </div>

                    <div class="col-xs-12">
                        <!-- Blog-post start -->
                        <div class="blog-post">
                            <div class="row">
                                <div class="col-lg-6 p-top-60">
                                    <div class="blog-post-img">
                                        <img src="assets/images/blog.jpg" alt="Post Image"></img>
                                    </div>
                                </div>

                                <div class="col-lg-6 p-top-60 p-bottom-60">
                                    <article>
                                        <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                        </h3>
                                        <p class="author m-top-25">Writen by <a href="">Jhon Doe</a></p>

                                        <p class="post first-letter">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi fuga aperiam optio reprehenderit cum voluptas sint ipsum, in explicabo eaque nesciunt ducimus numquam debitis distinctio, nulla fugit id asperiores, facere.</p>

                                        <p class="details">
                                            <a href="" class="more">Continue Reading <span class="fa fa-angle-double-right"></span></a>
                                            <span class="comments"><i class="fa fa-comments-o"></i> 10</span>
                                        </p>
                                    </article>
                                </div>
                            </div>
                        </div><!-- Blog-post end -->
                    </div>

                </div><!-- Row end -->
            </div><!-- Container end -->
        </section><!-- Blog-top end -->


        <!-- Main-blog-post start -->
        <section class="main-blog-post">
            <div class="container">
                <div class="row">
                    <!-- Post area start -->
                    <div class="col-md-8 m-top-15">
                        <article class="p-top-50 p-bottom-40">
                            <h3 class="">Lorem ipsum dolor sit amet consectetur.
                            </h3>
                            <p class="author m-top-10 m-bottom-20">Writen by <a href="">Jhon Doe</a></p>

                            <div class="post-img">
                                <div class="date">
                                    24 dec <br></br>
                                    2016
                                </div>
                                <img src="assets/images/blog_post1.jpg" alt=""></img>
                            </div>

                            <p class="post first-letter m-top-15 m-bottom-10">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi fuga aperiam optio reprehenderit cum voluptas sint ipsum, in explicabo eaque nesciunt ducimus numquam debitis distinctio, nulla fugit id asperiores, facere.</p>
                            <p class="details">
                                <a href="" class="more">Continue Reading <span class="fa fa-angle-double-right"></span></a>
                                <span class="comments"><i class="fa fa-comments-o"></i> 10</span>
                            </p>
                        </article>

                        <article class="p-top-50 p-bottom-40">
                            <h3 class="">Lorem ipsum dolor sit amet consectetur.
                            </h3>
                            <p class="author m-top-10 m-bottom-20">Writen by <a href="">Jhon Doe</a></p>

                            <div class="post-img">
                                <div class="date">
                                    24 dec <br></br>
                                    2016
                                </div>
                                <img src="assets/images/blog_post2.jpg" alt=""></img>
                            </div>

                            <p class="post first-letter m-top-15 m-bottom-10">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi fuga aperiam optio reprehenderit cum voluptas sint ipsum, in explicabo eaque nesciunt ducimus numquam debitis distinctio, nulla fugit id asperiores, facere.</p>
                            <p class="details">
                                <a href="" class="more">Continue Reading <span class="fa fa-angle-double-right"></span></a>
                                <span class="comments"><i class="fa fa-comments-o"></i> 10</span>
                            </p>
                        </article>

                        <article class="p-top-50 p-bottom-40">
                            <h3 class="">Lorem ipsum dolor sit amet consectetur.
                            </h3>
                            <p class="author m-top-10 m-bottom-20">Writen by <a href="">Jhon Doe</a></p>

                            <div class="post-img">
                                <div class="date">
                                    24 dec <br></br>
                                    2016
                                </div>
                                <img src="assets/images/blog_post1.jpg" alt=""></img>
                            </div>

                            <p class="post first-letter m-top-15 m-bottom-10">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi fuga aperiam optio reprehenderit cum voluptas sint ipsum, in explicabo eaque nesciunt ducimus numquam debitis distinctio, nulla fugit id asperiores, facere.</p>
                            <p class="details">
                                <a href="" class="more">Continue Reading <span class="fa fa-angle-double-right"></span></a>
                                <span class="comments"><i class="fa fa-comments-o"></i> 10</span>
                            </p>
                        </article>
                    </div><!-- Post area end -->

                    <div class="col-md-4 m-top-50 sm-m-top-0 p-bottom-50 fix">
                        <!-- Sidebar start -->
                        <div class="sidebar">
                            <div class="catagories m-top-20">
                                <h4>Catagories</h4>
                                <ul class="catagories-menu m-top-15">
                                    <li><a href="">Interface Design</a></li>
                                    <li><a href="">Mobile App</a></li>
                                    <li><a href="">IOS Development</a></li>
                                    <li><a href="">UI Design</a></li>
                                </ul>
                            </div>

                            <div class="tags m-top-20">
                                <h4>Popular Tags</h4>
                                <ul class="m-top-15">
                                    <li><a href="">Androaid</a></li>
                                    <li><a href="">Mobile App</a></li>
                                    <li><a href="">Interface</a></li>
                                    <li><a href="">IOS Development</a></li>
                                    <li><a href="">UI Design</a></li>
                                    <li><a href="">Logo</a></li>
                                    <li><a href="">Identy</a></li>
                                    <li><a href="">Branding</a></li>
                                    <li><a href="">App Design</a></li>
                                </ul>
                            </div>
                        </div><!-- Sidebar end -->
                    </div>

                </div>
            </div>
        </section><!-- Main-blog-post start -->

</h:body>
<ui:include src="footer.xhtml"></ui:include>
</html>

src/main/webapp/landing page/contactus.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Contacter nous</title>
</h:head>

<ui:include src="head.xhtml"></ui:include>

<h:body>

        <!-- Contact Info start-->
        <section class="contact-info alfa fix">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="contact-item text-center m-top-80">
                            <span class="fa fa-phone"></span>
                            <p>+88 123 456 7890</p>
                            <p>+88 018 488 1669</p>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="contact-item text-center m-top-80">
                            <span class="fa fa-envelope-o"></span>
                            <p>sample@name.com</p>
                            <p>yourwebsite.com</p>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="contact-item text-center m-top-80">
                            <span class="fa fa-map-marker"></span>
                            <p>25 Green tower , Street name</p>
                            <p>Newyork city, USA</p>
                        </div>
                    </div>
                </div>
            </div>
        </section><!-- Contact Info end-->


        <!-- Contact Form start -->
        <section class="contact p-top-50">
            <form id="contact-form" action="#">
                <div class="container">

                    <div class="row contact-form">
                        <div class="col-sm-6 col-md-4 col-md-offset-2 m-top-30">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Enter your Name"></input>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4 m-top-30">
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Enter Your Email"></input>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-8 col-md-offset-2 m-top-30">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Subject"></input>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-8 col-md-offset-2 m-top-30">
                            <div class="form-group">
                                <textarea class="form-control" placeholder="Your Message"></textarea>
                            </div>
                        </div>

                        <div class="col-sm-12 col-md-8 col-md-offset-2 m-top-25 text-center">
                            <button type="submit" class="btn btn-default btn-round">Send</button>
                        </div>
                    </div>

                </div>
            </form>
        </section><!-- Contact-form end -->


        <!-- Map -->
        <section id="map"></section>

</h:body>
<ui:include src="footer.xhtml"></ui:include>
</html>

src/main/webapp/landing page/domaine.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>Domaines de recherches</title>
    </h:head>

    <ui:include src="head.xhtml"></ui:include>

    <h:body>

    </h:body>
    <ui:include src="footer.xhtml"></ui:include>
</html>

src/main/webapp/landing page/equipes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>personnels</title>
</h:head>

<ui:include src="head.xhtml"></ui:include>

<h:body>

    <h:form id="form">
        <p:dataGrid var="team" value="#{teamDataGridView.teams}" columns="3" layout="grid"
                    rows="12" paginator="true" id="la"
                    paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                    rowsPerPageTemplate="6,12,16">

            <f:facet name="header">
                Nos Equipes
            </f:facet>

            <!--<h:link action="#{teamDataGridView.membre}" value="equipes">
                <f:param name="selectedteam" value="#{teamDataGridView.selectedteam}"></f:param>-->


                <p:panel header="#{team.nom}" style="text-align:center">
                    <h:panelGrid columns="1" style="width:100%">
                        <div class="icon">
                            <i class="fa fa-flask"></i>
                        </div>

                        <h:outputText value="#{team.description}" />

                        <p:commandLink update=":form:carDetail" oncomplete="PF('carDialog').show()" title="View Detail">
                            <h:outputText styleClass="ui-icon ui-icon-search" style="margin:0 auto;" />
                            <f:setPropertyActionListener value="#{team}" target="#{teamDataGridView.selectedTeam}" />
                        </p:commandLink>
                    </h:panelGrid>
                </p:panel>

            <!--</h:link>-->



        </p:dataGrid>

        <p:dialog header="team Info" widgetVar="teamDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
            <p:outputPanel id="teamDetail" style="text-align:center;">
                <p:panelGrid  columns="2" rendered="#{not empty teamDataGridView.selectedTeam}" columnClasses="label,value">
                    <f:facet name="header">
                        <div class="icon">
                            <i class="fa fa-flask"></i>
                        </div>
                    </f:facet>

                    <h:outputText value="Nom:" />
                    <h:outputText value="#{teamDataGridView.selectedTeam.nom}" />

                    <h:outputText value="Description:" />
                    <h:outputText value="#{teamDataGridView.selectedTeam.description}"/>

                    <h:outputText value="Chef de team:" />
                    <h:outputText value="#{teamDataGridView.selectedTeam.chefEquipe.nom}" />
                </p:panelGrid>
            </p:outputPanel>
        </p:dialog>
    </h:form>

</h:body>
<ui:include src="footer.xhtml"></ui:include>
</html>

src/main/webapp/landing page/evenement.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Domaines de recherches</title>
</h:head>

<ui:include src="head.xhtml"></ui:include>

<h:body>

</h:body>
<ui:include src="footer.xhtml"></ui:include>
</html>

src/main/webapp/landing page/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<!-- Footer Widget section -->
<h:body>
<section class="bg-primary">

    <div class="container">
        <div class="row">
            <div class="main-weidget p-top-80 p-bottom-80">
                <div class="col-md-3">
                    <div class="weidget-item">
                        <h4 class="text-white">Company</h4>
                        <ul class="m-top-20">
                            <li><a href="home.html">Home</a></li>
                            <li><a href="#">About us</a></li>
                            <li><a href="pricing.html">Pricing</a></li>
                            <li><a href="contact.html">Contact us</a></li>
                        </ul>
                    </div>
                </div><!-- End off col-sm-3 -->

                <div class="col-md-3 sm-m-top-40">
                    <div class="weidget-item">
                        <h4 class="text-white">Quick Links</h4>
                        <ul class="m-top-20">
                            <li><a href=""> Designers</a></li>
                            <li><a href=""> Pricing plan</a></li>
                            <li><a href=""> Services</a></li>
                            <li><a href=""> Download</a></li>
                        </ul>
                    </div>
                </div><!-- End off col-sm-3 -->

                <div class="col-md-2 sm-m-top-40">
                    <div class="weidget-item">
                        <h4 class="text-white">Conditions</h4>
                        <ul class="m-top-20">
                            <li><a href=""> Online support</a></li>
                            <li><a href=""> Privacy</a></li>
                            <li><a href=""> Terms</a></li>
                            <li><a href=""> Policy</a></li>
                            <li><a href="../dashboard/pages/login.xhtml">Admin</a></li>
                        </ul>
                    </div>
                </div><!-- End off col-sm-3 -->

                <div class="col-md-4 sm-m-top-40">
                    <div class="weidget-item">
                        <h4 class="text-white">Get connected</h4>
                        <ul class="list-inline socail m-top-20">
                            <li><a href=""><span class="social_facebook"></span></a></li>
                            <li><a href=""><span class="social_twitter"></span></a></li>
                            <li><a href=""><span class="social_googleplus"></span></a></li>
                        </ul>
                    </div>
                </div><!-- End off col-md-4 -->

            </div>
        </div><!-- End off main widget-->

    </div><!-- End off container -->
</section><!-- End off footer widget Section -->


<!--Footer section-->
<footer class="footer bg-info p-top-20 p-bottom-20">
    <div class="scrollup">
        <a href="#" class="hvr-hang"><span class="arrow_up"></span></a>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="hv2-main-footer wow fadeInUp">
                    <div class="row">

                        <div class="col-md-12">
                            <div class="copyright-text text-center">
                                <p class="text-white">Made with <i class="fa fa-heart"></i> by <a class="text-white" href="https://bootstrapthemes.co" target="_blank">Bootstrap Themes</a> 2016. All Rights Reserved</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer><!-- End off footer Section-->

        <!-- JS includes -->
<script src="assets/js/vendor/jquery-1.11.2.min.js"></script>
<script src="assets/js/vendor/bootstrap.js"></script>

<script src="assets/js/jquery.easing.1.3.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.touchswipe/1.6.18/jquery.touchSwipe.min.js"></script>
<script src="assets/js/bootsnav.js"></script>
<script src="assets/js/jquery.formchimp.js"></script>

<script src="assets/js/plugins.js"></script>
<script src="assets/js/main.js"></script>
<script type="text/javascript">
/*---------------------------------------------*
 * WOW
 ---------------------------------------------*/

var wow = new WOW({
    mobile: false // trigger animations on mobile devices (default is true)
});
wow.init();
</script>
</h:body>
</html>

src/main/webapp/landing page/laboratoires.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>personnels</title>
</h:head>

<ui:include src="head.xhtml"></ui:include>

<h:body>

    <h:form id="form">
        <p:dataGrid var="labo" value="#{dataGridView.labos}" columns="3" layout="grid"
                    rows="12" paginator="true" id="la"
                    paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                    rowsPerPageTemplate="6,12,16">

            <f:facet name="header">
               Nos Laboratoires
            </f:facet>

            <p:panel header="#{labo.nom}" style="text-align:center">
                <h:panelGrid columns="1" style="width:100%">
                    <div class="icon">
                        <i class="fa fa-flask"></i>
                    </div>





                    <h:commandLink action="#{teamDataGridView.printTeam}" value = "Afficher les equipes">
                        <f:param name="laboId" value="#{labo.id}"  />
                    </h:commandLink>

                    <!--<h:outputText value="#{labo.adresse}" />-->

                    <p:commandLink update=":form:laboDetail" oncomplete="PF('laboDialog').show()" title="View Detail">
                        <h:outputText styleClass="ui-icon ui-icon-search" style="margin:0 auto;" />
                        <f:setPropertyActionListener value="#{labo}" target="#{dataGridView.selectedLabo}" />
                    </p:commandLink>
                </h:panelGrid>
            </p:panel>


        </p:dataGrid>

        <p:dialog header="Labo Info" widgetVar="laboDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
            <p:outputPanel id="laboDetail" style="text-align:center;">
                <p:panelGrid  columns="2" rendered="#{not empty dataGridView.selectedLabo}" columnClasses="label,value">
                    <f:facet name="header">
                        <div class="icon">
                            <i class="fa fa-flask"></i>
                        </div>
                    </f:facet>

                    <h:outputText value="Nom:" />
                    <h:outputText value="#{dataGridView.selectedLabo.nom}" />

                    <h:outputText value="Adresse:" />
                    <h:outputText value="#{dataGridView.selectedLabo.adresse}" />

                    <h:outputText value="Description:" />
                    <h:outputText value="#{dataGridView.selectedLabo.description}"/>

                    <h:outputText value="Chef de labo:" />
                    <h:outputText value="#{dataGridView.selectedLabo.administrateurLabo.nom}" />
                </p:panelGrid>
            </p:outputPanel>
        </p:dialog>
    </h:form>

</h:body>
<ui:include src="footer.xhtml"></ui:include>
</html>